// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_BG_H
#define _UI_COMP_BG_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT bg
#define UI_COMP_BG_BG 0
#define _UI_COMP_BG_NUM 1
lv_obj_t *ui_bg_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
