// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_albumPage_screen_init(void)
{
    ui_albumPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_albumPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_albumPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_albumPage, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_albumPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumPage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg = ui_bg_create(ui_albumPage);
    lv_obj_set_x(ui_bg, -1);
    lv_obj_set_y(ui_bg, -1);

    ui_loadingBar1 = ui_loadingBar_create(ui_albumPage);
    lv_obj_set_x(ui_loadingBar1, -4);
    lv_obj_set_y(ui_loadingBar1, 81);

    ui_bg1 = ui_bg_create(ui_albumPage);
    lv_obj_set_x(ui_bg1, 0);
    lv_obj_set_y(ui_bg1, 0);

    lv_obj_add_event_cb(ui_albumPage, ui_event_albumPage, LV_EVENT_ALL, NULL);

}
