// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_settingPage_screen_init(void)
{
    ui_settingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settingPage, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settingPage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_settingPage);
    lv_img_set_src(ui_Image6, &ui_img_bg_greap_10x10_png);
    lv_obj_set_width(ui_Image6, lv_pct(100));
    lv_obj_set_height(ui_Image6, lv_pct(100));
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiName = lv_label_create(ui_settingPage);
    lv_obj_set_width(ui_wifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiName, -100);
    lv_obj_set_y(ui_wifiName, -70);
    lv_obj_set_align(ui_wifiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiName, "WIFI Name");
    lv_obj_set_style_text_color(ui_wifiName, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiPass = lv_label_create(ui_settingPage);
    lv_obj_set_width(ui_wifiPass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiPass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiPass, -94);
    lv_obj_set_y(ui_wifiPass, -26);
    lv_obj_set_align(ui_wifiPass, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiPass, "WIFI PassWord");
    lv_obj_set_style_text_color(ui_wifiPass, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiNameIn = lv_textarea_create(ui_settingPage);
    lv_obj_set_width(ui_wifiNameIn, 169);
    lv_obj_set_height(ui_wifiNameIn, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_wifiNameIn, 58);
    lv_obj_set_y(ui_wifiNameIn, -78);
    lv_obj_set_align(ui_wifiNameIn, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_wifiNameIn, 20);
    lv_textarea_set_one_line(ui_wifiNameIn, true);
    lv_obj_set_style_text_color(ui_wifiNameIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiNameIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_wifiNameIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiNameIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiNameIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifiNameIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiNameIn, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiNameIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiNameIn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifiNameIn, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_wifiNameIn, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiNameIn, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_wifiPassIn = lv_textarea_create(ui_settingPage);
    lv_obj_set_width(ui_wifiPassIn, 170);
    lv_obj_set_height(ui_wifiPassIn, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_wifiPassIn, 57);
    lv_obj_set_y(ui_wifiPassIn, -36);
    lv_obj_set_align(ui_wifiPassIn, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_wifiPassIn, 20);
    lv_textarea_set_one_line(ui_wifiPassIn, true);
    lv_textarea_set_password_mode(ui_wifiPassIn, true);
    lv_obj_set_style_text_color(ui_wifiPassIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiPassIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_wifiPassIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiPassIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiPassIn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifiPassIn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiPassIn, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiPassIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiPassIn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifiPassIn, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_connectBtn = lv_btn_create(ui_settingPage);
    lv_obj_set_width(ui_connectBtn, 103);
    lv_obj_set_height(ui_connectBtn, 44);
    lv_obj_set_x(ui_connectBtn, 20);
    lv_obj_set_y(ui_connectBtn, 84);
    lv_obj_set_align(ui_connectBtn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_connectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connectBtn, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_connectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_connectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_connectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_connectBtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "connect");

    ui_backBtn = lv_btn_create(ui_settingPage);
    lv_obj_set_width(ui_backBtn, 103);
    lv_obj_set_height(ui_backBtn, 44);
    lv_obj_set_x(ui_backBtn, -20);
    lv_obj_set_y(ui_backBtn, 84);
    lv_obj_set_align(ui_backBtn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_backBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backBtn, lv_color_hex(0xD1743B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_backBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_backBtn);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "back");

    ui_Keyboard1 = lv_keyboard_create(ui_settingPage);
    lv_obj_set_height(ui_Keyboard1, 111);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_wifiNameIn, ui_event_wifiNameIn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiPassIn, ui_event_wifiPassIn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectBtn, ui_event_connectBtn, LV_EVENT_ALL, NULL);

}
